#pragma once

#include "CoreMinimal.h"

class UAnimBlueprint;
class UEdGraphPin;
class UAnimSequence;
class UAnimationAsset;
class UBlendSpace1D;
class USkeletalMesh;
class USkeleton;

struct FLocomotionAnimSet
{
	UBlendSpace1D* Locomotion = nullptr;
	UAnimSequence* Idle = nullptr;
	UBlendSpace1D* Crouch = nullptr;
	UBlendSpace1D* Pickaxe = nullptr;
	UAnimSequence* JumpStart = nullptr;
	UAnimSequence* JumpStartRun = nullptr;     // Fortnite's forward jump, for jumping while running
	UAnimSequence* JumpLoop = nullptr;
	UAnimSequence* Land = nullptr;
};

/**
 * Builds real, editable Anim Blueprint graphs:
 *  - Locomotion: State Machine (Locomotion / Crouch / Pickaxe / Jump / Fall / Land)
 *      -> Layered blend from spine_01 with the "UpperBody" slot (weapons) -> DefaultSlot -> Output Pose
 *  - Parts: Copy Pose From Mesh (attached parent) -> Output Pose, used by heads, hats, etc.
 */
class FAnimBlueprintGenerator
{
public:
	/** Montage slot for weapon hold/fire/reload; lives in its own slot group so it never cancels emotes */
	static const FName UpperBodySlot;

	/** Slot (in a group of its own) for the additive layers of Fortnite: weapon recoil and the aim pose, played on top of everything else */
	static const FName AdditiveSlot;
	static void RegisterAdditiveSlot(USkeleton* Skeleton);
	static bool EnsureAdditiveLayer(UAnimBlueprint* AnimBlueprint);

	static UAnimBlueprint* CreateLocomotionBlueprint(const FString& Folder, const FString& Name, USkeleton* Skeleton, USkeletalMesh* PreviewMesh, const FLocomotionAnimSet& AnimSet);
	/** Rebuilds the graph of a previously generated locomotion blueprint in place (keeps the asset and its references) */
	static UAnimBlueprint* RebuildLocomotionBlueprint(UAnimBlueprint* AnimBlueprint, const FLocomotionAnimSet& AnimSet);
	static UAnimBlueprint* CreatePartsBlueprint(const FString& Folder, const FString& Name, USkeleton* Skeleton, USkeletalMesh* PreviewMesh);

	/** A chain of extra bones (tail, ears...) simulated with Anim Dynamics */
	struct FPartsChain
	{
		FName Start;
		FName End;
	};

	/** Additive bone space offset of a blink pose */
	struct FPartsBoneOffset
	{
		FName Bone;
		FVector Location = FVector::ZeroVector;
		FRotator Rotation = FRotator::ZeroRotator;
	};

	/**
	 * (Re)builds a parts Anim Blueprint: Copy Pose from the body, then the eye blink (eyelid offsets scaled by
	 * BlinkAlpha of UFortnitePortingPartsAnimInstance) and a spring/gravity simulation for each tail chain.
	 */
	static void BuildPartsGraph(UAnimBlueprint* AnimBlueprint, USkeleton* Skeleton, const TArray<FPartsChain>& Chains, const TArray<FPartsBoneOffset>& BlinkBones);

	static void RegisterUpperBodySlot(USkeleton* Skeleton);

	/**
	 * Inserts the upper body weapon layer between the state machine and DefaultSlot.
	 * Safe to call on blueprints generated by older versions; returns true if the graph changed (and was recompiled).
	 */
	static bool EnsureUpperBodyLayer(UAnimBlueprint* AnimBlueprint);

	/**
	 * Checks that the UpperBody slot of a generated blueprint really reaches the output (cached locomotion -> slot -> layered blend
	 * from spine_01 at weight 1) and rebuilds the layer when it does not. Returns true if the graph changed (and was recompiled).
	 */
	static bool RepairUpperBodyLayer(UAnimBlueprint* AnimBlueprint);

	/**
	 * Adds left hand IK (Modify Bone rotation + Two Bone IK on hand_l) right before the Output Pose,
	 * driven by UFortnitePortingAnimInstance::LeftHandIK*. Returns true if the graph changed (not compiled).
	 */
	static bool EnsureLeftHandIK(UAnimBlueprint* AnimBlueprint);

	/** Turns the upper body (from spine_01) by FortnitePortingAnimInstance::UpperBodyTwist so a two handed weapon at rest does not point across the body */
	static bool EnsureWeaponTwist(UAnimBlueprint* AnimBlueprint);


	/**
	 * Sleeves and shirt shoulders hang from dfrm_upperarm_l/r, which only follow the clavicle: in Fortnite a constraint
	 * makes them copy the arm's rotation, here nothing did and the arm left the sleeve. Builds a post process Anim
	 * Blueprint for a body mesh, compiled against the mesh's own skeleton, that adds that copy (the arm's turn from its
	 * reference pose, in parent space) to whatever animation plays. Returns null when the body has no such bones.
	 */
	static UAnimBlueprint* CreateBodyFixBlueprint(const FString& Folder, const FString& Name, USkeletalMesh* Body);

	/** Upgrades the Pickaxe state to "locomotion legs + pickaxe upper body". Returns true if changed (not compiled). */
	static bool EnsurePickaxeLayer(UAnimBlueprint* AnimBlueprint);

	/** Replaces the knee slide's rifle arms (clavicles down) by the unarmed/pickaxe pose, weighted by SlideArmsAlpha. Returns true if changed (not compiled). */
	static bool EnsureSlideArms(UAnimBlueprint* AnimBlueprint);

private:
	static bool AddUpperBodyLayer(UAnimBlueprint* AnimBlueprint);
	/** Cuts the cached locomotion + UpperBody slot + layered blend in front of CutIn (the pose input that will read the layer) */
	static bool InsertUpperBodyLayer(UAnimBlueprint* AnimBlueprint, UEdGraphPin* CutIn);
	static UAnimBlueprint* BuildLocomotionGraph(UAnimBlueprint* AnimBlueprint, USkeleton* Skeleton, const FLocomotionAnimSet& AnimSet);

	static UAnimBlueprint* CreateAnimBlueprint(const FString& Folder, const FString& Name, USkeleton* Skeleton, USkeletalMesh* PreviewMesh, UClass* ParentClass);
	static void Compile(UAnimBlueprint* AnimBlueprint);
};
