#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Engine/EngineTypes.h"
#include "InputCoreTypes.h"
#include "FortnitePortingCharacterComponent.generated.h"

class ACharacter;
class UAnimInstance;
class UAnimMontage;
class UAudioComponent;
class UMeshComponent;
class USkeletalMesh;
class USkeletalMeshComponent;
class UFortnitePortingEmoteData;
class UFortnitePortingGliderData;
class UFortnitePortingPickaxeData;
class UFortnitePortingStyleData;
class UMaterialInterface;
class UFortnitePortingWeaponData;

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnFortnitePortingInventoryChanged);
class AFortnitePortingVehicle;
class AFortnitePortingWeapon;

/** Root bone path of a Fortnite mantle, relative to its last key: X = forward cm, Z = up cm (sampled per key) */
USTRUCT(BlueprintType)
struct FORTNITEPORTINGRUNTIME_API FFortnitePortingMantlePath
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting")
	TArray<FVector> Points;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting")
	float Length = 0.0f;

	bool IsValid() const { return Points.Num() >= 2 && Length > KINDA_SMALL_NUMBER; }

	FVector Sample(float Time) const
	{
		const float Key = FMath::Clamp(Time / Length, 0.0f, 1.0f) * (Points.Num() - 1);
		const int32 Index = FMath::Min(FMath::FloorToInt(Key), Points.Num() - 2);
		return FMath::Lerp(Points[Index], Points[Index + 1], Key - Index);
	}
};

/**
 * Persistent state the server mirrors to every client so simulated proxies and late joiners reproduce what the owner
 * is doing. Transient events (shots, swings, reloads, slide, mantle) travel as multicasts instead.
 */
USTRUCT()
struct FORTNITEPORTINGRUNTIME_API FFortnitePortingNetState
{
	GENERATED_BODY()

	UPROPERTY()
	bool bPickaxe = false;

	UPROPERTY()
	bool bGliding = false;

	UPROPERTY()
	TObjectPtr<UFortnitePortingWeaponData> Weapon = nullptr;

	UPROPERTY()
	TObjectPtr<UFortnitePortingEmoteData> Emote = nullptr;

	/** Bumped every time an emote starts, so the same emote played twice replicates twice */
	UPROPERTY()
	uint8 EmoteSerial = 0;

	UPROPERTY()
	TObjectPtr<AFortnitePortingVehicle> Vehicle = nullptr;

	/** Sitting behind the driver instead of driving */
	UPROPERTY()
	bool bVehiclePassenger = false;
};

/** The look of one component before any style touched it, so styles can be undone */
USTRUCT()
struct FFortnitePortingStyleBaseline
{
	GENERATED_BODY()

	UPROPERTY()
	TObjectPtr<USkeletalMeshComponent> Component = nullptr;

	UPROPERTY()
	TObjectPtr<USkeletalMesh> Mesh = nullptr;

	UPROPERTY()
	TSubclassOf<UAnimInstance> AnimClass;

	UPROPERTY()
	TArray<TObjectPtr<UMaterialInterface>> Materials;

	UPROPERTY()
	bool bVisible = true;
};

/**
 * Added to every character blueprint generated by Fortnite Porting.
 * Handles pickaxe, weapons, vehicles, glider, emotes, mantling and the default keyboard controls.
 *
 * Multiplayer: the server is authoritative. The owning client sends requests (Request* -> Server_* RPCs), the server
 * runs the normal local code and mirrors the result in NetState / multicasts, and every machine plays the visuals.
 * Walking, jumping and crouching use the CharacterMovement prediction; slide and mantle are client authoritative.
 */
UCLASS(ClassGroup = (FortnitePorting), meta = (BlueprintSpawnableComponent), DisplayName = "Fortnite Porting Character")
class FORTNITEPORTINGRUNTIME_API UFortnitePortingCharacterComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UFortnitePortingCharacterComponent();

	/** Skeleton profile detected on import ("Female_Medium", "Male_Large"...), used to pick matching animations */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting")
	FName SkeletonProfile = TEXT("Male_Medium");

	UPROPERTY(EditAnywhere, BlueprintReadWrite, ReplicatedUsing = OnRep_Pickaxe, Category = "Fortnite Porting|Cosmetics")
	TObjectPtr<UFortnitePortingPickaxeData> Pickaxe;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, ReplicatedUsing = OnRep_Glider, Category = "Fortnite Porting|Cosmetics")
	TObjectPtr<UFortnitePortingGliderData> Glider;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Cosmetics")
	TArray<TObjectPtr<UFortnitePortingEmoteData>> Emotes;

	/**
	 * On BeginPlay, every weapon, emote, pickaxe and glider sent with Fortnite Porting (CosmeticsRoot) is added to
	 * this character, so a skin imported before an item still gets it. Pickaxe/Glider are only filled when empty.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Cosmetics")
	bool bAutoRegisterCosmetics = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Cosmetics", meta = (EditCondition = "bAutoRegisterCosmetics"))
	FString CosmeticsRoot = TEXT("/Game/FortnitePorting");

	/** Every pickaxe / glider found in the project (locker lists) */
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, Transient, Category = "Fortnite Porting|Cosmetics")
	TArray<TObjectPtr<UFortnitePortingPickaxeData>> AvailablePickaxes;

	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, Transient, Category = "Fortnite Porting|Cosmetics")
	TArray<TObjectPtr<UFortnitePortingGliderData>> AvailableGliders;

	// ── Styles ───────────────────────────────────────────────────────────────

	/** Every style of this outfit (set when a skin with styles is sent): channels such as Style, Glasses or Tail */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Style")
	TObjectPtr<UFortnitePortingStyleData> StyleData;

	/** Option picked in each channel of StyleData (a missing entry is 0: the outfit's own look). Replicated. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, ReplicatedUsing = OnRep_StyleSelection, Category = "Fortnite Porting|Style")
	TArray<int32> StyleSelection;

	/** Picks the option of every channel. Clients ask the server, which replicates the choice to everyone. */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Style")
	void SetStyleSelection(const TArray<int32>& Selection);

	/** Puts the parts and materials of the picked options on the character */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Style")
	void ApplyStyleSelection();

	UFUNCTION(Server, Reliable)
	void Server_SetStyleSelection(const TArray<int32>& Selection);

	/** Swaps the pickaxe (re-equipping it when it was in the hands) */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Cosmetics")
	void SetPickaxe(UFortnitePortingPickaxeData* NewPickaxe);

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Cosmetics")
	void SetGlider(UFortnitePortingGliderData* NewGlider);

	/** Scans CosmeticsRoot for exported cosmetics (called on BeginPlay when bAutoRegisterCosmetics) */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Cosmetics")
	void RegisterProjectCosmetics();

	/**
	 * Epic's master skeleton mesh for this body profile (set when the skin is sent). Fortnite bodies lack the
	 * animated weapon_r/weapon_l bones; a hidden copy of this mesh runs the same animations so held items can
	 * follow weapon_r exactly like in the game.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	TObjectPtr<USkeletalMesh> WeaponRigMesh;

	/** Draws hand_r (body) and weapon_r (rig) axes in game and logs the rig state every 2 s, to diagnose grips */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	bool bDebugWeaponRig = false;

	/**
	 * Two-handed items (scythes, staffs...) carry a handle bone/socket in Fortnite; the game IKs the left hand onto it.
	 * The exported animations only place the right hand, so without this the left hand floats next to the handle.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	bool bLeftHandIK = true;

	/** The left hand takes the turn of the weapon's "Underbarrel" socket, plus this offset, instead of the turn the hold animation gives it */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	bool bLeftHandFromSocket = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	FRotator LeftHandSocketRotation = FRotator::ZeroRotator;

	/** The "Underbarrel" socket is where the palm goes: the wrist (the hand bone) is this far back along the forearm, in cm */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	float LeftHandPalmOffset = 7.0f;

	/** How far the left arm may reach for the fore end, as a share of its length; a longer fore end has the hand slide back along the barrel */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons", meta = (ClampMin = "0.5", ClampMax = "1.0"))
	float LeftHandMaxReach = 0.96f;

	/** Crouching shrinks the capsule the camera boom hangs from; keep the camera at standing height (Fortnite does) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	bool bKeepCameraHeightWhenCrouching = true;

	/** Bone or socket on the held item where the left hand grips */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	FName LeftHandGripSocket = TEXT("Melee_TwoHanded_Handle");

	/** Weapons sent from Items; cycled with WeaponKey */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, ReplicatedUsing = OnRep_Weapons, Category = "Fortnite Porting|Weapons")
	TArray<TObjectPtr<UFortnitePortingWeaponData>> Weapons;

	UPROPERTY(BlueprintAssignable, Category = "Fortnite Porting|Weapons")
	FOnFortnitePortingInventoryChanged OnInventoryChanged;

	/** Turn the character towards the camera on every shot */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	bool bFaceCameraWhenFiring = true;

	/** How close a vehicle must be to get in with InteractKey */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Vehicles")
	float VehicleSearchRadius = 1500.0f;

	/** Mid mantle (Fortnite Hurdle_Mantle_100Up); also the fallback when Low/High are missing */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	TObjectPtr<UAnimMontage> MantleMontage;

	/** Ledges below MantleLowMaxHeight (Hurdle_Mantle_50Up) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	TObjectPtr<UAnimMontage> MantleMontageLow;

	/** Ledges above MantleHighMinHeight (Hurdle_Mantle_200Up) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	TObjectPtr<UAnimMontage> MantleMontageHigh;

	/** Root paths of the three mantles (filled by the importer), the character follows them during the climb */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	FFortnitePortingMantlePath MantlePath;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	FFortnitePortingMantlePath MantlePathLow;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	FFortnitePortingMantlePath MantlePathHigh;

	/** Fortnite's hurdles last ~0.2 s: they are slowed down so the climb lasts at least this long */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleMinDuration = 0.4f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleLowMaxHeight = 75.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleHighMinHeight = 150.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	bool bEnableMantle = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleMinHeight = 45.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleMaxHeight = 210.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleReach = 75.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleDuration = 0.6f;

	/** Fraction of the mantle after which its animation starts blending back into locomotion (overlap = no snap at the end) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal", meta = (ClampMin = "0.5", ClampMax = "1"))
	float MantleBlendOutStart = 0.8f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal")
	float MantleBlendOutTime = 0.3f;

	/**
	 * Fortnite's mantle landing (LandToSprint) keeps the sprint going for a moment. It is cut as soon as the player
	 * stops pushing forward or sprinting, and never lasts longer than this (seconds), so the character doesn't keep
	 * running on its own after climbing.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Traversal", meta = (ClampMin = "0"))
	float MantleLandMaxTime = 0.35f;

	/** Applies the speeds below on BeginPlay so the generated blend spaces line up with the movement */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	bool bApplyMovementSettings = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	float JogSpeed = 450.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	float SprintSpeed = 650.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	float CrouchSpeed = 250.0f;

	/**
	 * How fast the character turns towards where it moves (degrees/s). The template's 500 lets the body lag behind
	 * the camera while running, so the run cycle points one way and the capsule moves another; Fortnite turns fast.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	float TurnRate = 1000.0f;

	/** Eases the body toward the movement direction (fast start, soft finish) instead of turning at a constant rate */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement")
	bool bSmoothTurning = true;

	/** Higher = the body faces the new direction sooner (12: ~90% of a 180 turn in 0.2 s). TurnRate caps it. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Movement", meta = (EditCondition = "bSmoothTurning", ClampMin = "1"))
	float TurnSharpness = 12.0f;

	/**
	 * Replaces the template's floaty jump (gravity x1, 500 cm/s) with Fortnite-like values on BeginPlay:
	 * heavier gravity, a quick fixed-height jump and more air control
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Jump")
	bool bApplyJumpSettings = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Jump")
	float GravityScale = 2.0f;

	/** With GravityScale 2 this gives a ~1.45 m high, ~0.8 s jump */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Jump")
	float JumpZVelocity = 760.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Jump")
	float AirControl = 0.6f;

	/** How fast horizontal speed is lost in the air when no direction is held */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Jump")
	float BrakingDecelerationFalling = 400.0f;

	/** Sprint + SlideKey (or CrouchKey) slides along the ground like Fortnite */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	bool bEnableSlide = true;

	/** Knee slide (Fortnite KneeSlideInitiate + KneeSliding), filled by the importer */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	TObjectPtr<UAnimMontage> SlideMontage;

	/** The outfit's own lobby idle (sent with the skin), looped by PlayLobbyIdle in the lobby / locker */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Lobby")
	TObjectPtr<UAnimMontage> LobbyIdleMontage;

	/** Lobby pose: loops LobbyIdleMontage with the pickaxe put away (restored by StopLobbyIdle) */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Lobby")
	void PlayLobbyIdle();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Lobby")
	void StopLobbyIdle();

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting|Lobby")
	bool IsInLobbyIdle() const { return bLobbyIdle; }

	/** Minimum ground speed to start a slide (sprinting is also required) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideMinSpeed = 350.0f;

	/** Speed added when the slide starts */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideBoost = 150.0f;

	/** Speed lost per second on flat ground (downhill slopes add speed, uphill slopes remove more) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideDeceleration = 380.0f;

	/** Share of gravity applied along slopes */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideSlopeGravity = 0.6f;

	/** The slide ends (and the character keeps crouching) below this speed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideEndSpeed = 300.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideMaxSpeed = 1400.0f;

	/** Steering while sliding, degrees per second */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Slide")
	float SlideTurnRate = 70.0f;

	/** Poll the keys below every frame (no Input Actions needed). Disable to drive everything from your own input */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	bool bEnableDefaultControls = true;

	/** While true the fire, swing and reload buttons do nothing (the game sets it while the player is building) */
	UPROPERTY(BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	bool bCombatBlocked = false;

	/** Holding this key aims down the sights of the weapon in the hands (zoom, sight, scope for the sniper) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Aiming")
	FKey AimKey = EKeys::RightMouseButton;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Aiming")
	bool bEnableAiming = true;

	/** Testing: aims as if the aim key was held down */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Aiming")
	bool bDebugForceAim = false;

	UPROPERTY(BlueprintReadOnly, Category = "Fortnite Porting|Aiming")
	bool bAiming = false;

	/** 0 = hip, 1 = fully aimed */
	UFUNCTION(BlueprintPure, Category = "Fortnite Porting|Aiming")
	float GetAimAlpha() const { return AimAlpha; }

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey SprintKey = EKeys::LeftShift;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey CrouchKey = EKeys::C;

	/** Slides while sprinting (the template's crouch key). CrouchKey slides too. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey SlideKey = EKeys::LeftControl;

	/** Jumps out of a slide (a crouched character cannot jump on its own) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey JumpKey = EKeys::SpaceBar;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey PickaxeKey = EKeys::One;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey SwingKey = EKeys::LeftMouseButton;

	/** Seconds after a swing ends during which the next click plays the follow-up swing (Fortnite's left arm swing) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	float SwingComboWindow = 0.35f;

	/** Pickaxe swing speed: the lobby swings Fortnite ships are slower than its in game harvesting */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls", meta = (ClampMin = "0.5", ClampMax = "3"))
	float SwingPlayRate = 1.6f;

	/** Fraction of a swing after which the next one starts (the rest is recovery, skipped when chaining) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls", meta = (ClampMin = "0.3", ClampMax = "1"))
	float SwingChainPoint = 0.55f;

	/** Damage of a pickaxe swing to players, built pieces and props. Every pickaxe imported with Fortnite Porting gets it. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Pickaxe", meta = (ClampMin = "0"))
	float PickaxeDamage = 20.0f;

	/** How far in front of the character a swing lands, in cm */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Pickaxe", meta = (ClampMin = "50"))
	float PickaxeReach = 230.0f;

	/** A click this recent still counts when the swing reaches its chain point, so spamming clicks acts like holding */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	float SwingInputBuffer = 0.45f;

	/** Pressed while falling to open/close the glider */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey GliderKey = EKeys::SpaceBar;

	/** Master volume of the emote music, for you and for what you hear of other players (the mixer still ducks on top of it) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Emote", meta = (ClampMin = "0", ClampMax = "1"))
	float EmoteMusicVolume = 0.25f;

	/** Plays the next emote of the Emotes list */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey EmoteKey = EKeys::B;

	/** Equips the next weapon of the Weapons list (then holsters) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey WeaponKey = EKeys::Two;

	/** Fires the equipped weapon (hold for automatic weapons) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey FireKey = EKeys::LeftMouseButton;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey ReloadKey = EKeys::R;

	/** Get in / out of the nearest vehicle */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Controls")
	FKey InteractKey = EKeys::E;

	/** Spawn already holding the pickaxe, like in Fortnite. PickaxeKey still toggles it. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Pickaxe")
	bool bEquipPickaxeOnStart = true;

	/** The pickaxe is never shown (its swing still plays, with empty hands): for enemies that fight with their hands */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Pickaxe")
	bool bHidePickaxe = false;

	/** The emote goes on while the character walks (a zombie shambling) instead of stopping at the first step */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Emote")
	bool bEmoteWhileMoving = false;

	/**
	 * Local nudge applied on top of the pickaxe's authored offset (rotate/move it around its own grip).
	 * Needed when the body mesh has no "weapon_r" socket and the pickaxe falls back to attaching to the
	 * hand bone directly: tune this live in PIE until it sits right, since resending the pickaxe from
	 * the app would overwrite an edit made on DA_<Pickaxe> instead.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Pickaxe")
	FTransform PickaxeGripAdjustment;

	/** Same idea as PickaxeGripAdjustment, for the currently held weapon (main + offhand meshes) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fortnite Porting|Weapons")
	FTransform WeaponGripAdjustment;

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Pickaxe")
	void EquipPickaxe();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Pickaxe")
	void UnequipPickaxe();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Pickaxe")
	void TogglePickaxe();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Pickaxe")
	void SwingPickaxe();

	/** Hides (or shows again) the pickaxe for good: it is still swung, with empty hands */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Pickaxe")
	void SetHidePickaxe(bool bHide);


	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Emote")
	bool PlayEmote(UFortnitePortingEmoteData* Emote);

	/** Stops the dance; the montage blends out over BlendOutTime seconds and the music fades with it */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Emote")
	void StopEmote(float BlendOutTime = 0.25f);

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Glider")
	bool DeployGlider();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Glider")
	void StopGliding();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Traversal")
	bool TryMantle();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Weapons")
	bool EquipWeapon(UFortnitePortingWeaponData* Weapon);

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Weapons")
	void UnequipWeapon();

	/** Equips the next weapon; after the last one the weapon is holstered */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Weapons")
	void CycleWeapon();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Weapons")
	bool FireWeapon();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Weapons")
	bool ReloadWeapon();

	/** Adds a world pickup to Weapons, equips it and removes it from the level */
	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Weapons")
	void PickupWeapon(AFortnitePortingWeapon* Pickup);

	void RequestEquipInventoryWeapon(UFortnitePortingWeaponData* Weapon);
	void RequestDropInventoryWeapon(UFortnitePortingWeaponData* Weapon);
	void RequestReorderInventoryWeapon(UFortnitePortingWeaponData* Weapon, int32 NewIndex);
	void SetGameplayInputBlocked(bool bBlocked);

	UFUNCTION(Server, Reliable)
	void Server_EquipInventoryWeapon(UFortnitePortingWeaponData* Weapon);

	UFUNCTION(Server, Reliable)
	void Server_DropInventoryWeapon(UFortnitePortingWeaponData* Weapon);

	UFUNCTION(Server, Reliable)
	void Server_ReorderInventoryWeapon(UFortnitePortingWeaponData* Weapon, int32 NewIndex);

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Vehicles")
	bool EnterVehicle(AFortnitePortingVehicle* Vehicle);

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Vehicles")
	void ExitVehicle();

	/** Nearest vehicle that can be entered, or null */
	UFUNCTION(BlueprintPure, Category = "Fortnite Porting|Vehicles")
	AFortnitePortingVehicle* FindEnterableVehicle() const;

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Movement")
	void SetSprinting(bool bSprint);

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Slide")
	bool TryStartSlide();

	UFUNCTION(BlueprintCallable, Category = "Fortnite Porting|Slide")
	void StopSlide();

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool IsSliding() const { return bSliding; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool HasPickaxeEquipped() const { return bPickaxeEquipped; }

	/** One handed / dual pickaxes play their own hold montage: the Anim Blueprint must not show its two handed pickaxe pose under it */
	bool PickaxeUsesOwnHold() const;

	/** Left hand IK target in body component space; false when the held item has no two-handed grip */
	bool GetLeftHandIKTarget(FTransform& OutHand, FVector& OutJoint) const;

	/** Degrees the upper body is turned (about the vertical) to bring a two handed weapon at rest in front of the body */
	float GetUpperBodyTwistYaw() const { return UpperBodyTwistYaw; }

	/** Degrees the upper body is tilted up or down so the weapon points where the crosshair is while aiming */
	float GetUpperBodyAimPitch() const { return UpperBodyAimPitch * AimPitchSign; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool IsGliding() const { return bGliding; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool IsMantling() const { return bMantling; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool IsEmoting() const { return ActiveEmoteMontage != nullptr; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool HasWeaponEquipped() const { return CurrentWeapon != nullptr; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	UFortnitePortingWeaponData* GetCurrentWeapon() const { return CurrentWeapon; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	int32 GetAmmoInMagazine() const { return AmmoInMagazine; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	bool IsInVehicle() const { return CurrentVehicle != nullptr; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting|Vehicles")
	bool IsVehiclePassenger() const { return CurrentVehicle != nullptr && bIsPassenger; }

	UFUNCTION(BlueprintPure, Category = "Fortnite Porting")
	AFortnitePortingVehicle* GetCurrentVehicle() const { return CurrentVehicle; }

	// ── Emote music mixing (see UFortnitePortingEmoteMixer) ──────────────────

	/** True when this emote belongs to the player on this machine (its music always wins over other players') */
	bool IsEmoteLocal() const { return DrivesMovement(); }

	/** Volume (0-1) the music of this emote has on this machine right now */
	float GetEmoteMusicGain() const { return EmoteMusicGain; }

	/** Fades the music of this emote to Gain over FadeTime seconds. Called by the emote mixer. */
	void SetEmoteMusicGain(float Gain, float FadeTime);

	// ── Networking ───────────────────────────────────────────────────────────

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	/**
	 * Requests coming from the local player (default controls, UI). They run directly on the server / offline and are
	 * forwarded to the server otherwise. The plain functions above (EquipPickaxe, FireWeapon...) are the local
	 * implementation every machine runs once the server has decided.
	 */
	void RequestTogglePickaxe();
	void RequestSwingPickaxe();
	void RequestCycleWeapon();
	void RequestFire();
	void RequestReload();
	void RequestGlider(bool bDeploy);
	void RequestEmote(UFortnitePortingEmoteData* Emote);
	void RequestEnterVehicle(AFortnitePortingVehicle* Vehicle);
	void RequestExitVehicle();
	void RequestSprint(bool bSprint);

	UFUNCTION(Server, Reliable)
	void Server_TogglePickaxe();

	UFUNCTION(Server, Reliable)
	void Server_SwingPickaxe();

	UFUNCTION(Server, Reliable)
	void Server_CycleWeapon();

	UFUNCTION(Server, Reliable)
	void Server_Fire(FVector_NetQuantize Origin, FVector_NetQuantizeNormal Direction);

	UFUNCTION(Server, Reliable)
	void Server_Reload();

	UFUNCTION(Server, Reliable)
	void Server_Glider(bool bDeploy);

	UFUNCTION(Server, Reliable)
	void Server_PlayEmote(UFortnitePortingEmoteData* Emote);

	UFUNCTION(Server, Reliable)
	void Server_EnterVehicle(AFortnitePortingVehicle* Vehicle);

	UFUNCTION(Server, Reliable)
	void Server_ExitVehicle();

	UFUNCTION(Server, Reliable)
	void Server_Sprint(bool bSprint);

	/** The aim button went down or up on the owner: everybody else shows the aim pose */
	UFUNCTION(Server, Reliable)
	void Server_SetAiming(bool bAim);

	/** Owner tells the server it started / stopped sliding; the server mirrors the visual to the other clients */
	UFUNCTION(Server, Reliable)
	void Server_SlideState(bool bSlide);

	UFUNCTION(Server, Reliable)
	void Server_MantleState(bool bMantle, UAnimMontage* Montage, float PlayRate);

	UFUNCTION(NetMulticast, Unreliable)
	void Multicast_FireFX(FVector_NetQuantizeNormal Direction, FVector_NetQuantize End, bool bHit);

	UFUNCTION(NetMulticast, Reliable)
	void Multicast_ReloadFX();

	UFUNCTION(NetMulticast, Reliable)
	void Multicast_SwingFX(int32 Section);

	/** The thud of a pickaxe landing on wood, stone or metal, heard by everybody near it */
	UFUNCTION(NetMulticast, Unreliable)
	void Multicast_PickaxeImpact(FName Surface, FVector_NetQuantize Point);

	UFUNCTION(NetMulticast, Reliable)
	void Multicast_SlideVisual(bool bSlide);

	UFUNCTION(NetMulticast, Reliable)
	void Multicast_MantleVisual(bool bMantle, UAnimMontage* Montage, float PlayRate);

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

private:
	// ── Networking internals ─────────────────────────────────────────────────

	UPROPERTY(ReplicatedUsing = OnRep_NetState)
	FFortnitePortingNetState NetState;

	UFUNCTION()
	void OnRep_Weapons();

	UFUNCTION()
	void OnRep_NetState();

	UFUNCTION()
	void OnRep_Pickaxe();

	UFUNCTION()
	void OnRep_StyleSelection();

	/** Components created for parts a style adds (destroyed and rebuilt on every change) */
	UPROPERTY(Transient)
	TArray<TObjectPtr<USkeletalMeshComponent>> StyleParts;

	UPROPERTY(Transient)
	TArray<FFortnitePortingStyleBaseline> StyleBaselines;

	bool bStyleBaselineTaken = false;

	UFUNCTION()
	void OnRep_Glider();

	/** Re-creates the machine's local state from the mirrored NetState (clients only) */
	void ApplyNetState();

	/** Server: copies the local state into NetState so it replicates */
	void SyncNetStateFromLocal();

	/** True in any networked game (listen server, client) */
	bool IsNetworked() const;

	/** True on the server and offline: this machine decides what happens */
	bool HasNetAuthority() const;

	/** True when this machine simulates the character's own movement: the owning player, or offline */
	bool DrivesMovement() const;

	/** Server / offline half of FireWeapon: validates, spends ammo, deals damage and tells everybody to play the visuals */
	bool FireWeaponAuthoritative(FVector Origin, FVector Direction);
	bool ReloadAuthoritative();

	/** Visual half of FireWeapon / ReloadWeapon, played on every machine */
	void FireFX(const FVector& Direction, const FVector& End, bool bHit);
	float ReloadFX();

	/** Slide / mantle state without touching the movement component: used by machines that do not own the pawn */
	void SetSlideVisual(bool bSlide);
	void SetMantleVisual(bool bMantle, UAnimMontage* Montage, float PlayRate);

	/** Tells the other machines about a slide / mantle that this machine is driving */
	void BroadcastSlide(bool bSlide);
	void BroadcastMantle(bool bMantle, UAnimMontage* Montage, float PlayRate);

	/** Lets the server accept the owner's position while it drives a slide / mantle the server does not simulate */
	void SetServerAcceptsClientPosition(bool bAccept) const;

	uint8 LastAppliedEmoteSerial = 0;
	int32 EmotePlayCount = 0;
	int32 SyncedEmotePlayCount = 0;
	UPROPERTY(Transient)
	TObjectPtr<UFortnitePortingEmoteData> PendingEmote;
	float PendingEmoteElapsed = 0.0f;

	ACharacter* GetCharacter() const;
	USkeletalMeshComponent* GetBodyMesh() const;
	UAnimInstance* GetAnimInstance() const;
	float PlayMontage(UAnimMontage* Montage, float PlayRate = 1.0f) const;
	bool PlayOrQueueEmote(UFortnitePortingEmoteData* Emote);
	void PlayMontageSection(UAnimMontage* Montage, int32 SectionIndex, float PlayRate = 1.0f) const;
	void StartSwingSection(UAnimMontage* Swing, int32 Section);

	void TickAim(float DeltaTime);
	void ApplyAimMontage(bool bWantsAim);
	void EndAim();

	/** What the other machines know of the aiming of this character */
	UPROPERTY(Replicated)
	bool bAimingNet = false;
	bool bAimSent = false;
	bool bHeldHidden = false;
	float PendingKick = 0.0f;
	float AimAlpha = 0.0f;
	float AimBaseFOV = 90.0f;
	float AimBaseArm = 0.0f;
	bool bAimBaseSaved = false;
	bool bBodyHiddenForScope = false;
	TSharedPtr<class SWidget> ReticleWidget;

	/** The moment the pickaxe lands: whatever is in front of the character takes PickaxeDamage (server / standalone only) */
	void PickaxeHit();
	void TickPickaxeCombo(float DeltaTime);
	void StopMontage(UAnimMontage* Montage, float BlendOutTime) const;
	void SetMontagePlayRate(UAnimMontage* Montage, float PlayRate) const;

	void CreateWeaponRig();

	/** Socket/bone on the body to attach to; OutDriverBone is set when the offset must follow a weapon rig bone */
	FName ResolveHandAttachment(FName RequestedSocket, const TCHAR* DebugLabel, FName& OutDriverBone) const;

	/** Offset + grip adjustment, plus the animated offset of DriverBone from its parent on the weapon rig */
	/** ItemMesh: the attached asset; a skeletal item is shifted so its root bone (not the component) lands on the grip, as in Fortnite */
	FTransform ComputeAttachTransform(const FTransform& Offset, const FTransform& Adjustment, FName DriverBone, const UObject* ItemMesh = nullptr) const;

	void HandleDefaultControls();
	void TickEmote();
	void TickGlider();
	void TickMantle(float DeltaTime);
	void TickSlide(float DeltaTime);
	void TickTurning(float DeltaTime);
	bool CanSlide() const;

	/**
	 * Pickaxe equip/swing montages from older imports play on DefaultSlot, which replaces the whole body and
	 * freezes the legs while walking. Moves them to the UpperBody slot (legs keep running, like Fortnite).
	 */
	static void UseUpperBodySlot(UAnimMontage* Montage);
	void TickWeapon(float DeltaTime);
	void TickVehicle();

	/**
	 * Re-applies PickaxeGripAdjustment/WeaponGripAdjustment to the already-attached meshes every frame,
	 * so dragging the values in the Details panel while in PIE moves the item live instead of only
	 * taking effect the next time it's equipped.
	 */
	void TickGripAdjustments();

	void SetPickaxeVisible(bool bVisible);

	/**
	 * False for montages whose animation is an additive pose/noise (zero scale on every bone): played as a normal
	 * pose they collapse the upper body and whatever is held with it. Cached per montage.
	 */
	static bool IsUsableMontage(const UAnimMontage* Montage);

	/** Keeps Montage on its last frame (the item-in-hand pose at the end of an equip) as a hold pose */
	void HoldLastFrame(UAnimMontage* Montage);
	void TickPickaxeHold();
	void TickEmoteSounds(float DeltaTime);
	void StopEmoteSounds();
	void DestroyWeaponVisuals();
	void PlayHoldMontage();

	/**
	 * The montage actually played for a weapon animation. Hold / jog poses come as montages a few hundredths of a second long
	 * whose looping depends on how they were imported, so a transient copy that loops for hours is played instead (bLoop); when
	 * the Anim Blueprint turns out to have no working UpperBody slot every weapon montage is copied onto DefaultSlot (full body).
	 */
	UAnimMontage* ResolveWeaponMontage(UAnimMontage* Source, bool bLoop);
	FName WeaponSlotName() const;
	void CheckUpperBodySlot(float DeltaTime, UAnimInstance* AnimInstance);
	void StopWeaponPoseMontages(float BlendOutTime);

	/** Transient copies made by ResolveWeaponMontage, by source montage */
	UPROPERTY(Transient)
	TMap<TObjectPtr<UAnimMontage>, TObjectPtr<UAnimMontage>> WeaponMontageCopies;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveHoldMontage;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveJogMontage;

	/** ActiveWeaponMontage is the draw animation (the left hand may already ride the weapon's grip socket) */
	bool bActiveMontageIsEquip = false;

	/** Set once the UpperBody slot is proven not to reach the final pose (see CheckUpperBodySlot) */
	bool bUpperBodySlotBroken = false;
	bool bUpperBodySlotChecked = false;
	float UpperBodySlotSettled = 0.0f;
	void FinishExitVehicle();
	bool EnterVehicleAs(AFortnitePortingVehicle* Vehicle, bool bPassenger);

	/**
	 * Fortnite's skeleton names the right-hand attach point "weapon_r". A re-rigged or non-standard
	 * body mesh may not have it, which otherwise makes the item snap to the mesh root (near the feet/
	 * pelvis) instead of the hand. Falls back to the actual hand bone, logging what it picked so a
	 * mismatch can be diagnosed from the Output Log.
	 */
	static FName ResolveAttachSocket(const USkeletalMeshComponent* Body, FName RequestedSocket, const TCHAR* DebugLabel);

	/** Applies Adjustment as a local nudge (its own rotation/location) on top of Offset, in Offset's space. */
	static FTransform ApplyGripAdjustment(const FTransform& Offset, const FTransform& Adjustment);

	UPROPERTY(Transient)
	TArray<TObjectPtr<UMeshComponent>> PickaxeComponents;

	/** Hidden master skeleton copy that provides weapon_r (see WeaponRigMesh) */
	UPROPERTY(Transient)
	TObjectPtr<USkeletalMeshComponent> WeaponRig;

	/** Parallel to PickaxeComponents / OffhandComponents: rig bone driving each attachment, or None */
	TArray<FName> PickaxeDriverBones;
	TArray<FName> OffhandDriverBones;
	FName WeaponDriverBone;
	float WeaponRigDebugTimer = 0.0f;
	void DebugWeaponRig(float DeltaTime);

	void UpdateLeftHandIK();
	void UpdateWeaponTwist(float DeltaTime);
	void UpdateWeaponFit(float DeltaTime);

	/** Left hand IK for a two handed weapon: keeps the hand on the point of the weapon it holds at rest while the body walks or turns */
	bool UpdateWeaponLeftHandIK(float DeltaTime);
	FTransform LeftHandOnWeapon = FTransform::Identity;
	bool bLeftHandOnWeaponValid = false;
	bool bWeaponGripSaved = false;
	float WeaponGripSettle = 0.0f;

	/** Turn (in the space of the socket the weapon hangs from) that lines the barrel up with the line between the hands, found once the hold pose is steady */
	FQuat WeaponFitRotation = FQuat::Identity;
	int32 WeaponFitPasses = 0;
	bool bWeaponFitKnown = false;
	float WeaponFitSettle = 0.0f;
	float UpperBodyTwistYaw = 0.0f;
	float UpperBodyAimPitch = 0.0f;

	/** Share of the camera's pitch the torso takes while aiming (the arms follow it, the rest is the pose's own) */
	UPROPERTY(EditAnywhere, Category = "Fortnite Porting|Aiming", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float AimPitchShare = 0.7f;

	/** Which way the torso turns for a camera pitch: +1 or -1, depending on how the skeleton is oriented */
	UPROPERTY(EditAnywhere, Category = "Fortnite Porting|Aiming")
	float AimPitchSign = 1.0f;

	/** Fortnite's relaxed carry points the weapon ahead and this many degrees to the character's left: the weapon is turned in the hand until its barrel sits there */
	UPROPERTY(EditAnywhere, Category = "Weapons")
	float RelaxedWeaponAngle = 20.0f;

	/** Degrees the barrel is tipped on that relaxed carry, negative pointing at the ground */
	UPROPERTY(EditAnywhere, Category = "Weapons")
	float RelaxedWeaponPitch = -5.0f;

	/** Only a barrel further than this from the relaxed carry is turned back onto it; anything nearer is the animator's hold and is left alone.
	 *  It is deliberately wide: a real hold pose puts both hands on the weapon, and turning the weapon out of them tears the grip apart during
	 *  the equip, fire and reload montages, where the left hand IK is off and cannot follow. Only a weapon held right across the body is caught. */
	UPROPERTY(EditAnywhere, Category = "Weapons")
	float CrossBodyWeaponAngle = 75.0f;
	void UpdateCameraCrouchOffset();
	bool bCameraBaseCached = false;
	float CameraBaseZ = 0.0f;
	bool bLeftHandIKValid = false;
	FTransform LeftHandIKTransform;
	FVector LeftHandIKJoint = FVector::ZeroVector;

	UPROPERTY(Transient)
	TObjectPtr<USkeletalMeshComponent> GliderComponent;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveEmoteMontage;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveGlideMontage;

	UPROPERTY(Transient)
	TObjectPtr<UFortnitePortingWeaponData> CurrentWeapon;

	UPROPERTY(Transient)
	TObjectPtr<AFortnitePortingWeapon> WeaponActor;

	UPROPERTY(Transient)
	TArray<TObjectPtr<UMeshComponent>> OffhandComponents;

	/** Fire/reload/equip montage currently overriding the hold pose */
	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveWeaponMontage;

	UPROPERTY(Transient)
	TObjectPtr<AFortnitePortingVehicle> CurrentVehicle;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveVehicleMontage;

	bool bPickaxeEquipped = false;
	bool bGliding = false;
	bool bMantling = false;
	bool bSprinting = false;
	bool bSliding = false;
	float SlideSpeed = 0.0f;
	float SlideElapsed = 0.0f;
	float SlideCooldown = 0.0f;
	/** Pickaxe combo: which swing section plays next, and how long a follow-up click still chains into it */
	int32 NextSwingSection = 0;
	float SwingComboTimer = 0.0f;
	bool bSwingQueued = false;
	float TimeSinceSwingPress = 100.0f;
	FVector SlideDirection = FVector::ForwardVector;

	/** Movement values replaced while sliding */
	float SavedGroundFriction = 8.0f;
	float SavedBrakingFriction = 0.0f;
	float SavedBrakingDecelerationWalking = 2000.0f;
	float SavedMaxAcceleration = 2048.0f;
	float SavedMaxWalkSpeedCrouched = 250.0f;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveSlideMontage;

	float FallTime = 0.0f;
	float MantleElapsed = 0.0f;
	float MantleActiveDuration = 0.0f;
	bool bMantleFollowsCurves = false;
	FFortnitePortingMantlePath ActiveMantlePath;
	float MantlePlayRate = 1.0f;
	FVector MantleForward = FVector::ForwardVector;
	FVector MantleCorrection = FVector::ZeroVector;

	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActiveMantleMontage;
	float MantleCooldown = 0.0f;
	FVector MantleStart = FVector::ZeroVector;
	FVector MantleTarget = FVector::ZeroVector;
	float MantleEntrySpeed = 0.0f;
	bool bMantleBlendingOut = false;
	bool bMantleLanding = false;
	bool bLobbyIdle = false;
	bool bPickaxeBeforeLobby = false;
	float MantleLandTime = 0.0f;

	/** Hold pose montage of a one handed / dual pickaxe currently playing */
	UPROPERTY(Transient)
	TObjectPtr<UAnimMontage> ActivePickaxeHold;

	UPROPERTY(Transient)
	TObjectPtr<UFortnitePortingEmoteData> ActiveEmoteData;

	UPROPERTY(Transient)
	TArray<TObjectPtr<UAudioComponent>> EmoteAudio;

	/** Parallel to EmoteAudio: which entry of the emote Sounds each audio component is playing */
	TArray<int32> EmoteAudioIndex;

	float EmoteElapsed = 0.0f;
	int32 NextEmoteSound = 0;

	/** An emote with music repeats until the player moves: the montage loops one section and the music follows it */
	bool bEmoteLooping = false;
	float EmoteLoopStart = 0.0f;
	float LastEmotePosition = 0.0f;

	/** Current volume of this emote's music (1 = full), and where the mixer wants it to go */
	float EmoteMusicGain = 1.0f;
	float EmoteMusicTarget = 1.0f;
	float EmoteMusicFadeRate = 0.0f; // volume units per second; 0 = jump straight to the target

	/** Moves EmoteMusicGain towards its target and applies it to the playing audio */
	void TickEmoteMusicFade(float DeltaTime);

	/** The music that sets the pace (the longest track). It loops by itself and is never restarted: the dance adapts to it */
	int32 EmoteMasterSound = INDEX_NONE;

	/** Waves switched to looping for this emote, put back when it ends */
	TArray<TWeakObjectPtr<class USoundWave>> ForcedLoopWaves;

	void SetupEmoteLoop(UAnimMontage* Montage);
	void SetMontageNextSection(UAnimMontage* Montage, FName Section, FName NextSection) const;
	void SpawnEmoteSound(int32 SoundIndex, float StartTime);
	void RestartEmoteSoundsForLoop();
	void ReorderInventoryWeapon(UFortnitePortingWeaponData* Weapon, int32 NewIndex);

	float CachedAirControl = 0.35f;
	int32 NextEmoteIndex = 0;

	int32 CurrentWeaponIndex = INDEX_NONE;
	bool bGameplayInputBlocked = false;

	/** Owner only: the other players do not need to know how many bullets are left */
	UPROPERTY(Replicated)
	int32 AmmoInMagazine = 0;
	float FireCooldown = 0.0f;
	float ReloadRemaining = 0.0f;
	bool bExitingVehicle = false;
	bool bIsPassenger = false;
	float VehicleCooldown = 0.0f;
	TEnumAsByte<ECollisionEnabled::Type> CachedCapsuleCollision = ECollisionEnabled::QueryAndPhysics;
};
